name: DisguiseCraft
main: pgDev.bukkit.DisguiseCraft.DisguiseCraft
version: 3.8
author: PG Dev Team
authors: [Tux2, DrKabob, Devil Boy]
description: Turn into any mob you want!
softdepend: [ProtocolLib]

commands:
   disguise:
      description: Set a disguise.
      aliases: [d, dc, dis]
      usage: /<command>
   undisguise:
      description: Remove a disguise.
      aliases: [u, ud, undis]
      usage: /<command>

permissions:
    disguisecraft.*:
        default: false
        description: Can use any DisguiseCraft functionality.
        children:
            disguisecraft.update: true
            disguisecraft.other.*: true
            disguisecraft.seer: true
            disguisecraft.notarget: true
            disguisecraft.notarget.strict: true
            disguisecraft.burning: true
            disguisecraft.player: true
            disguisecraft.mob.*: true
    disguisecraft.update:
        default: op
        description: Can be notified of plugin updates.
    disguisecraft.other.*:
        default: op
        description: Can use any of the disguise commands affecting others.
        children:
            disguisecraft.other.disguise: true
            disguisecraft.other.undisguise: true
    disguisecraft.other.disguise:
        default: op
        description: Can disguise other players.
    disguisecraft.other.undisguise:
        default: op
        description: Can undisguise other players.
    disguisecraft.seer:
        default: false
        description: Can see through disguises.
    disguisecraft.notarget:
        default: true
        description: Is not targeted by mobs while disguised.
    disguisecraft.notarget.strict:
        default: op
        description: Not targeted even after attacking a mob.
    disguisecraft.burning:
        default: op
        description: Can have a burning disguise.
    disguisecraft.drop:
        default: op
        description: Can drop their disguise.
    disguisecraft.player.*:
        default: op
        description: Can disguise as any other player.
    disguisecraft.mob.*:
        default: op
        description: Can disguise as any mob.
        children:
            disguisecraft.mob.bat: true
            disguisecraft.mob.blaze: true
            disguisecraft.mob.cavespider: true
            disguisecraft.mob.chicken: true
            disguisecraft.mob.chicken.baby: true
            disguisecraft.mob.cow: true
            disguisecraft.mob.cow.baby: true
            disguisecraft.mob.creeper: true
            disguisecraft.mob.creeper.charged: true
            disguisecraft.mob.enderdragon: true
            disguisecraft.mob.enderman: true
            disguisecraft.mob.enderman.hold: true
            disguisecraft.mob.ghast: true
            disguisecraft.mob.giant: true
            disguisecraft.mob.irongolem: true
            disguisecraft.mob.magmacube: true
            disguisecraft.mob.magmacube.size.*: true
            disguisecraft.mob.mushroomcow: true
            disguisecraft.mob.mushroomcow.baby: true
            disguisecraft.mob.ocelot: true
            disguisecraft.mob.ocelot.baby: true
            disguisecraft.mob.ocelot.cat.*: true
            disguisecraft.mob.pig: true
            disguisecraft.mob.pig.baby: true
            disguisecraft.mob.pig.saddled: true
            disguisecraft.mob.pigzombie: true
            disguisecraft.mob.sheep: true
            disguisecraft.mob.sheep.baby: true
            disguisecraft.mob.sheep.color.*: true
            disguisecraft.mob.silverfish: true
            disguisecraft.mob.skeleton: true
            disguisecraft.mob.slime: true
            disguisecraft.mob.slime.size.*: true
            disguisecraft.mob.snowman: true
            disguisecraft.mob.spider: true
            disguisecraft.mob.squid: true
            disguisecraft.mob.villager: true
            disguisecraft.mob.villager.baby: true
            disguisecraft.mob.villager.occupation.*: true
            disguisecraft.mob.witch: true
            disguisecraft.mob.wither: true
            disguisecraft.mob.wolf: true
            disguisecraft.mob.wolf.baby: true
            disguisecraft.mob.wolf.tamed: true
            disguisecraft.mob.wolf.aggressive: true
            disguisecraft.mob.zombie: true
    disguisecraft.mob.bat:
        default: op
        description: Can disguise as a bat.
    disguisecraft.mob.blaze:
        default: op
        description: Can disguise as a blaze.
    disguisecraft.mob.cavespider:
        default: op
        description: Can disguise as a cave spider.
    disguisecraft.mob.chicken:
        default: op
        description: Can disguise as a chicken.
    disguisecraft.mob.chicken.baby:
        default: op
        description: Can disguise as a baby chicken.
    disguisecraft.mob.cow:
        default: op
        description: Can disguise as a cow.
    disguisecraft.mob.cow.baby:
        default: op
        description: Can disguise as a baby cow.
    disguisecraft.mob.creeper:
        default: op
        description: Can disguise as a creeper.
    disguisecraft.mob.creeper.charged:
        default: op
        description: Can disguise as a charged creeper.
    disguisecraft.mob.enderdragon:
        default: op
        description: Can disguise as a ender dragon.
    disguisecraft.mob.enderman:
        default: op
        description: Can disguise as a enderman.
    disguisecraft.mob.enderman.hold:
        default: op
        description: Can hold blocks as an enderman.
    disguisecraft.mob.ghast:
        default: op
        description: Can disguise as a ghast.
    disguisecraft.mob.giant:
        default: op
        description: Can disguise as a giant.
    disguisecraft.mob.irongolem:
        default: op
        description: Can disguise as an iron golem.
    disguisecraft.mob.magmacube:
        default: op
        description: Can disguise as a magma cube.
    disguisecraft.mob.magmacube.size.*:
        default: op
        description: Can disguise as a magmacube of any size.
        children:
            disguisecraft.mob.magmacube.size.tiny: true
            disguisecraft.mob.magmacube.size.small: true
            disguisecraft.mob.magmacube.size.big: true
            disguisecraft.mob.magmacube.size.bigger: true
            disguisecraft.mob.magmacube.size.massive: true
            disguisecraft.mob.magmacube.size.godzilla: true
    disguisecraft.mob.magmacube.size.tiny:
        default: op
        description: Can disguise as a magmacube of size tiny.
    disguisecraft.mob.magmacube.size.small:
        default: op
        description: Can disguise as a magmacube of size small.
    disguisecraft.mob.magmacube.size.big:
        default: op
        description: Can disguise as a magmacube of size big.
    disguisecraft.mob.magmacube.size.bigger:
        default: op
        description: Can disguise as a magmacube of size bigger.
    disguisecraft.mob.magmacube.size.massive:
        default: op
        description: Can disguise as a magmacube of size massive.
    disguisecraft.mob.magmacube.size.godzilla:
        default: op
        description: Can disguise as a magmacube of size godzilla.
    disguisecraft.mob.mushroomcow:
        default: op
        description: Can disguise as a mooshroom.
    disguisecraft.mob.mushroomcow.baby:
        default: op
        description: Can disguise as a baby mooshroom.
    disguisecraft.mob.ocelot:
        default: op
        description: Can disguise as an ocelot.
    disguisecraft.mob.ocelot.baby:
        default: op
        description: Can disguise as a baby ocelot.
    disguisecraft.mob.ocelot.cat.*:
        default: op
        description: Can disguise as a cat of any type.
        children:
            disguisecraft.mob.ocelot.cat.tabby: true
            disguisecraft.mob.ocelot.cat.tuxedo: true
            disguisecraft.mob.ocelot.cat.siamese: true
    disguisecraft.mob.ocelot.cat.tabby:
        default: op
        description: Can disguise as a tabby cat.
    disguisecraft.mob.ocelot.cat.tuxedo:
        default: op
        description: Can disguise as a tuxedo cat.
    disguisecraft.mob.ocelot.cat.siamese:
        default: op
        description: Can disguise as a siamese cat.
    disguisecraft.mob.pig:
        default: op
        description: Can disguise as a pig.
    disguisecraft.mob.pig.baby:
        default: op
        description: Can disguise as a baby pig.
    disguisecraft.mob.pig.saddled:
        default: op
        description: Can disguise as a saddled pig.
    disguisecraft.mob.pigzombie:
        default: op
        description: Can disguise as a zombie pigman.
    disguisecraft.mob.sheep:
        default: op
        description: Can disguise as a sheep.
    disguisecraft.mob.sheep.baby:
        default: op
        description: Can disguise as a baby sheep.
    disguisecraft.mob.sheep.color.*:
        default: op
        description: Can disguise as a sheep of any color.
        children:
            disguisecraft.mob.sheep.color.black: true
            disguisecraft.mob.sheep.color.blue: true
            disguisecraft.mob.sheep.color.brown: true
            disguisecraft.mob.sheep.color.cyan: true
            disguisecraft.mob.sheep.color.gray: true
            disguisecraft.mob.sheep.color.green: true
            disguisecraft.mob.sheep.color.lightblue: true
            disguisecraft.mob.sheep.color.lime: true
            disguisecraft.mob.sheep.color.magenta: true
            disguisecraft.mob.sheep.color.orange: true
            disguisecraft.mob.sheep.color.pink: true
            disguisecraft.mob.sheep.color.purple: true
            disguisecraft.mob.sheep.color.red: true
            disguisecraft.mob.sheep.color.silver: true
            disguisecraft.mob.sheep.color.white: true
            disguisecraft.mob.sheep.color.yellow: true
            disguisecraft.mob.sheep.color.sheared: true
    disguisecraft.mob.sheep.color.black:
        default: op
        description: Can disguise as a sheep of the color black.
    disguisecraft.mob.sheep.color.blue:
        default: op
        description: Can disguise as a sheep of the color blue.
    disguisecraft.mob.sheep.color.brown:
        default: op
        description: Can disguise as a sheep of the color brown.
    disguisecraft.mob.sheep.color.cyan:
        default: op
        description: Can disguise as a sheep of the color cyan.
    disguisecraft.mob.sheep.color.gray:
        default: op
        description: Can disguise as a sheep of the color gray.
    disguisecraft.mob.sheep.color.green:
        default: op
        description: Can disguise as a sheep of the color green.
    disguisecraft.mob.sheep.color.lightblue:
        default: op
        description: Can disguise as a sheep of the color light blue.
    disguisecraft.mob.sheep.color.lime:
        default: op
        description: Can disguise as a sheep of the color lime.
    disguisecraft.mob.sheep.color.magenta:
        default: op
        description: Can disguise as a sheep of the color magenta.
    disguisecraft.mob.sheep.color.orange:
        default: op
        description: Can disguise as a sheep of the color orange.
    disguisecraft.mob.sheep.color.pink:
        default: op
        description: Can disguise as a sheep of the color pink.
    disguisecraft.mob.sheep.color.purple:
        default: op
        description: Can disguise as a sheep of the color purple.
    disguisecraft.mob.sheep.color.red:
        default: op
        description: Can disguise as a sheep of the color red.
    disguisecraft.mob.sheep.color.silver:
        default: op
        description: Can disguise as a sheep of the color silver.
    disguisecraft.mob.sheep.color.white:
        default: op
        description: Can disguise as a sheep of the color white.
    disguisecraft.mob.sheep.color.yellow:
        default: op
        description: Can disguise as a sheep of the color yellow.
    disguisecraft.mob.sheep.color.sheared:
        default: op
        description: Can disguise as a sheared sheep.
    disguisecraft.mob.silverfish:
        default: op
        description: Can disguise as a silverfish.
    disguisecraft.mob.skeleton:
        default: op
        description: Can disguise as a skeleton.
    disguisecraft.mob.slime:
        default: op
        description: Can disguise as a slime.
    disguisecraft.mob.slime.size.*:
        default: op
        description: Can disguise as a slime of any size.
        children:
            disguisecraft.mob.slime.size.tiny: true
            disguisecraft.mob.slime.size.small: true
            disguisecraft.mob.slime.size.big: true
            disguisecraft.mob.slime.size.bigger: true
            disguisecraft.mob.slime.size.massive: true
            disguisecraft.mob.slime.size.godzilla: true
    disguisecraft.mob.slime.size.tiny:
        default: op
        description: Can disguise as a slime of size tiny.
    disguisecraft.mob.slime.size.small:
        default: op
        description: Can disguise as a slime of size small.
    disguisecraft.mob.slime.size.big:
        default: op
        description: Can disguise as a slime of size big.
    disguisecraft.mob.slime.size.bigger:
        default: op
        description: Can disguise as a slime of size bigger.
    disguisecraft.mob.slime.size.massive:
        default: op
        description: Can disguise as a slime of size massive.
    disguisecraft.mob.slime.size.godzilla:
        default: op
        description: Can disguise as a slime of size godzilla.
    disguisecraft.mob.snowman:
        default: op
        description: Can disguise as a snow golem.
    disguisecraft.mob.spider:
        default: op
        description: Can disguise as a spider.
    disguisecraft.mob.squid:
        default: op
        description: Can disguise as a squid.
    disguisecraft.mob.villager:
        default: op
        description: Can disguise as a villager.
    disguisecraft.mob.villager.baby:
        default: op
        description: Can disguise as a baby villager.
    disguisecraft.mob.villager.occupation.*:
        default: op
        description: Can disguise as a villager of any occupation.
        children:
            disguisecraft.mob.villager.occupation.librarian: true
            disguisecraft.mob.villager.occupation.priest: true
            disguisecraft.mob.villager.occupation.blacksmith: true
            disguisecraft.mob.villager.occupation.butcher: true
    disguisecraft.mob.villager.occupation.librarian:
        default: op
        description: Can disguise as a librarian villager.
    disguisecraft.mob.villager.occupation.priest:
        default: op
        description: Can disguise as a priest villager.
    disguisecraft.mob.villager.occupation.blacksmith:
        default: op
        description: Can disguise as a blacksmith villager.
    disguisecraft.mob.villager.occupation.butcher:
        default: op
        description: Can disguise as a butcher villager.
    disguisecraft.mob.witch:
        default: op
        description: Can disguise as a witch.
    disguisecraft.mob.wither:
        default: op
        description: Can disguise as a Wither Boss.
    disguisecraft.mob.wolf:
        default: op
        description: Can disguise as a wolf.
    disguisecraft.mob.wolf.baby:
        default: op
        description: Can disguise as a baby wolf.
    disguisecraft.mob.wolf.tamed:
        default: op
        description: Can disguise as a tamed wolf.
    disguisecraft.mob.wolf.aggressive:
        default: op
        description: Can disguise as a agressive wolf.
    disguisecraft.mob.zombie:
        default: op
        description: Can disguise as a zombie.